(load "mini-framework.scm")
(define (test)
  (with-handlers ((dragstart-handler "#draggables")
		  (dragover-handler "#body")
		  (drop-handler "#body"))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input))
		 (display (get-input)))
  (display "Test finished."))
